{
 "title": "PipelineMetrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(count(pipeline_job_duration_seconds == 0) - (count(pipeline_job_duration_seconds offset $__interval == 0) or (1-absent(pipeline_job_duration_seconds==NA)))) or 1- absent(pipeline_job_duration_seconds == 0)",
     "legendFormat": "Jobs"
    },
    {
     "expr": "(count(pipeline_task_duration_seconds == 0) - (count(pipeline_task_duration_seconds offset $__interval == 0) or (1-absent(pipeline_task_duration_seconds==NA)))) or 1- absent(pipeline_task_duration_seconds == 0)",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Completions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(pipeline_job_last_completion) - count(pipeline_job_last_completion offset $__interval )",
     "legendFormat": "Jobs"
    },
    {
     "expr": "count(pipeline_task_last_completion) - count(pipeline_task_last_completion offset $__interval )",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "(count(pipeline_job_last_failure) - (count(pipeline_job_last_failure offset $__interval == 0) or (1-absent(pipeline_job_last_failure==NA)))) or 1- absent(pipeline_job_last_failure == NA)",
     "legendFormat": "Jobs"
    },
    {
     "expr": "(count(pipeline_task_last_failure) - (count(pipeline_task_last_failure offset $__interval == 0) or (1-absent(pipeline_task_last_failure==NA)))) or 1- absent(pipeline_task_last_failure == NA)",
     "legendFormat": "Tasks"
    }
   ]
  },
  {
   "title": "Job Outlook",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (rate (pipeline_job_duration_seconds[10m])) by (jobId) * 600",
     "legendFormat": "{{jobId}}"
    }
   ]
  },
  {
   "title": "Task Outlook",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum (rate (pipeline_task_duration_seconds[2m])) by (taskId) * 120",
     "legendFormat": "{{taskId}}"
    }
   ]
  },
  {
   "title": "Top 10 job Executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "topk(10,count({__name__=\"pipeline_job_last_completion\"}) by (jobId))",
     "legendFormat": "{{jobId}}"
    }
   ]
  },
  {
   "title": "Top 10 task executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "topk(10,count({__name__=\"pipeline_task_last_completion\"}) by (taskId))",
     "legendFormat": "{{taskId}}"
    }
   ]
  },
  {
   "title": "Long Running Tasks(10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10,avg(pipeline_task_duration_seconds) by (taskId))",
     "legendFormat": "{{taskId}}"
    }
   ]
  },
  {
   "title": "Long Running Jobs(10)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10,avg(pipeline_job_duration_seconds) by (jobId))",
     "legendFormat": "{{jobId}}"
    }
   ]
  }
 ]
}